#
# $ make cleanup
#
# This playbook has been tested with Ubuntu 16.04 and Ansible 2.7.
#
- hosts: [127.0.0.1]
  connection: local

  tasks:

  - { name: "KeePassXC: Remove official PPA", become: yes, apt_repository: { repo: "ppa:phoerious/keepassxc", state: absent }, tags: [keepassxc] }
  - { name: "KeePassXC: Remove system packages", become: yes, apt: { pkg: [keepassxc], state: absent }, tags: [keepassxc] }
  - { name: "KeePassXC: Uninstall AppImage & artifacts", become: yes, file: { path: "{{ item }}", state: absent }, tags: [keepassxc], with_items: [
      "/usr/local/bin/keepassxc",
      "/usr/local/share/icons/keepassxc.png",
      "/usr/share/applications/org.keepassxc.KeePassXC.desktop"
    ] }

  - { name: "Franz: Uninstall AppImage & artifacts", file: { path: "{{ item }}", state: absent }, tags: [franz], with_items: [
      "/usr/local/bin/franz",
      "{{ ansible_env.HOME }}/.local/share/applications/appimagekit-franz.desktop",
      "{{ ansible_env.HOME }}/.local/share/icons/hicolor/16x16/apps/appimagekit-franz.png",
      "{{ ansible_env.HOME }}/.local/share/icons/hicolor/24x24/apps/appimagekit-franz.png",
      "{{ ansible_env.HOME }}/.local/share/icons/hicolor/32x32/apps/appimagekit-franz.png",
      "{{ ansible_env.HOME }}/.local/share/icons/hicolor/48x48/apps/appimagekit-franz.png",
      "{{ ansible_env.HOME }}/.local/share/icons/hicolor/64x64/apps/appimagekit-franz.png",
      "{{ ansible_env.HOME }}/.local/share/icons/hicolor/96x96/apps/appimagekit-franz.png",
      "{{ ansible_env.HOME }}/.local/share/icons/hicolor/128x128/apps/appimagekit-franz.png",
      "{{ ansible_env.HOME }}/.local/share/icons/hicolor/256x256/apps/appimagekit-franz.png",
      "{{ ansible_env.HOME }}/.local/share/icons/hicolor/512x512/apps/appimagekit-franz.png",
      "{{ ansible_env.HOME }}/.local/share/icons/hicolor/1024x1024/apps/appimagekit-franz.png"
    ] }

  - { name: "Skype: Remove system packages", become: yes, apt: { pkg: [skypeforlinux], state: absent }, tags: [skype] }

# vim: sw=2 ts=2 et :
